export const educationData = [
  {
    id: 1,
    title: "Gempa Bumi",
    icon: "🌍",
    description: "Getaran atau guncangan yang terjadi di permukaan bumi akibat pelepasan energi dari dalam bumi secara tiba-tiba.",
    tips: ["Berlindung di bawah meja kuat", "Jauhi jendela & kaca", "Matikan listrik & gas", "Tetap tenang dan jangan panik"],
    level: "Tinggi",
  },
  {
    id: 2,
    title: "Banjir",
    icon: "🌊",
    description: "Meluapnya air yang menggenangi daratan, umumnya disebabkan curah hujan tinggi atau luapan sungai.",
    tips: ["Evakuasi ke tempat tinggi", "Matikan listrik", "Bawa dokumen penting", "Pantau info BMKG"],
    level: "Sedang",
  },
  {
    id: 3,
    title: "Tanah Longsor",
    icon: "⛰️",
    description: "Perpindahan massa tanah atau batuan menuruni lereng akibat hujan deras atau gempa bumi.",
    tips: ["Hindari lereng terjal saat hujan", "Waspadai retakan tanah", "Kenali tanda-tanda awal", "Segera mengungsi jika ada peringatan"],
    level: "Tinggi",
  },
  {
    id: 4,
    title: "Tsunami",
    icon: "🌀",
    description: "Gelombang laut besar yang dipicu oleh gempa bawah laut, letusan gunung api, atau tanah longsor bawah laut.",
    tips: ["Jika gempa, langsung lari ke bukit", "Jangan tunggu peringatan resmi", "Ikuti jalur evakuasi", "Jangan kembali sebelum dinyatakan aman"],
    level: "Sangat Tinggi",
  },
  {
    id: 5,
    title: "Erupsi Gunung Berapi",
    icon: "🌋",
    description: "Keluarnya magma, gas, dan material vulkanik dari dalam bumi melalui kawah gunung berapi.",
    tips: ["Gunakan masker N95", "Evakuasi sesuai arahan PVMBG", "Hindari aliran sungai dari puncak", "Simpan dokumen berharga"],
    level: "Tinggi",
  },
  {
    id: 6,
    title: "Kebakaran Hutan",
    icon: "🔥",
    description: "Kebakaran di kawasan hutan akibat kekeringan panjang, kelalaian manusia, atau faktor alam lainnya.",
    tips: ["Jauhi area kebakaran", "Tutup mulut & hidung dengan masker", "Pantau arah angin", "Hubungi Damkar: 113"],
    level: "Sedang",
  },
];
